init
SversusN/gophermart pull request #1
Opened 2024-07-13 20:40 UTC by SversusN

2024-07-24 20:41 UTC, avhitrov requested changes
Годная реализация. Есть замечания - в комментариях к коду.

2024-07-24 20:41 UTC, avhitrov commented on cmd/gophermart/main.go
> +	newAgent.Start(ctx)
```suggestion
	wg := sync.WaitGroup
	newAgent.Start(ctx, wg)
```
В агенте поставить defer wg.Done(), а в процедуре шатдауна - wg.Wait(), чтобы нормально дождаться завершения работы агента.

2024-07-24 20:41 UTC, avhitrov commented on internal/accrualagent/service/service.go
> +	ticker := time.NewTicker(timeoutLoadOrdersDB * time.Second)
```
defer ticker.Stop()
```

2024-07-24 20:41 UTC, avhitrov commented on internal/accrualagent/service/service.go
> +	}
В ТЗ есть еще несколько статусов. В частности, статус 429 Too Many Requests. Их все необходимо соответствующим образом обрабатывать. Точнее, обрабатывать надо 429 и 200, остальные рассматривать, как ошибку.

2024-07-24 20:41 UTC, avhitrov commented on internal/accrualagent/service/service.go
> +	ticker := time.NewTicker(timeoutLoadOrdersDB * time.Second)
```
defer ticker.Stop()
```

2024-07-24 20:41 UTC, avhitrov commented on internal/controller/http/handlers/balance.go
> +	defer r.Body.Close()
https://t.me/bushigo/21

Не следует дергать функции от r.Body, не убедившись, что тело запроса не равно nil. Правильное положение данного defer - после проверки ошибки от io.ReadAll

2024-07-24 20:41 UTC, avhitrov commented on internal/repository/psql/migrations/00001_init.up.sql
> +);
Таблица полностью дублирует по наполнению accruals. Есть ли в ней смысл?

2024-07-24 20:41 UTC, avhitrov commented on internal/repository/psql/agent.go
> +	rows, err := a.db.QueryContext(ctx, "SELECT order_num, status FROM public.accruals WHERE status=$1 OR status=$2 LIMIT $3", model.StatusNEW.String(), model.StatusPROCESSING.String(), limit)
```suggestion
	rows, err := a.db.QueryContext(ctx, "SELECT order_num, status FROM public.accruals WHERE status=$1 OR status=$2 ORDER BY uploaded_at LIMIT $3", model.StatusNEW.String(), model.StatusPROCESSING.String(), limit)
```

2024-07-24 20:41 UTC, avhitrov commented on internal/repository/psql/agent.go
> +	tx, err := a.db.Begin()
А вот для этой операции транзакция не только не нужна, но и вредна. Записи между собой никак не связаны, так что если одна сохранится, а следующая по какой-то причине - нет, то мы получим консистентную базу. А при открытой транзакции - отлупятся обе.

2024-07-24 20:41 UTC, avhitrov commented on internal/repository/psql/withdraw.go
> +	}()
Не очень понятно, зачем дважды пытаться откатить транзакцию.

2024-07-25 06:52 UTC, SversusN commented on cmd/gophermart/main.go
> +	newAgent.Start(ctx)
+

2024-07-25 06:53 UTC, SversusN commented on internal/accrualagent/service/service.go
> +	ticker := time.NewTicker(timeoutLoadOrdersDB * time.Second)
+

2024-07-25 15:07 UTC, SversusN commented on internal/accrualagent/service/service.go
> +	}
+

2024-07-25 15:07 UTC, SversusN commented on internal/accrualagent/service/service.go
> +	}
Немного топорно, конечно =\

2024-07-25 15:12 UTC, SversusN commented on internal/controller/http/handlers/balance.go
> +	defer r.Body.Close()
упс, второй раз уже. Буду внимательней.

2024-07-25 15:16 UTC, SversusN commented on internal/repository/psql/migrations/00001_init.up.sql
> +);
Да, делал регистр для возможного клиента. Оставил по нелепейшему недосмотру, даже хендлер не сделал.=)

2024-07-25 15:16 UTC, SversusN commented on internal/repository/psql/migrations/00001_init.up.sql
> +);
+

2024-07-25 15:18 UTC, SversusN commented on internal/repository/psql/agent.go
> +	rows, err := a.db.QueryContext(ctx, "SELECT order_num, status FROM public.accruals WHERE status=$1 OR status=$2 LIMIT $3", model.StatusNEW.String(), model.StatusPROCESSING.String(), limit)
+

2024-07-25 15:20 UTC, SversusN commented on internal/repository/psql/agent.go
> +	tx, err := a.db.Begin()
+

2024-07-25 15:21 UTC, SversusN commented on internal/repository/psql/withdraw.go
> +	}()
не удалил лишнее.

2024-07-25 21:01 UTC, SversusN commented
С миграцией было ужасно стыдно D:<

2024-07-31 23:31 UTC, avhitrov approved these changes
Все ок.

2024-08-01 06:45 UTC, merged

2024-08-01 13:34 UTC, SversusN commented
https://t.me/bushigo/38
Ну не могу я пропустить сервисный слой и из хендлера дергать репу после проектов на C# 
xDDD